//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detalle()
        {
            this.DetalleLlamadas = new HashSet<DetalleLlamada>();
            this.DetalleUsoDatos = new HashSet<DetalleUsoDato>();
        }
    
        public int id { get; set; }
        public int idFactura { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<int> idUnidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleLlamada> DetalleLlamadas { get; set; }
        public virtual Factura Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleUsoDato> DetalleUsoDatos { get; set; }
    }
}
