//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesECOperador
    {
        public int id { get; set; }
        public System.DateTime HoraDeInicio { get; set; }
        public System.DateTime HoraDeFin { get; set; }
        public string NumeroDesde { get; set; }
        public string NumeroHacia { get; set; }
        public int idEstadoDeCuentaOperador { get; set; }
    
        public virtual EstadoDeCuentaOperador EstadoDeCuentaOperador { get; set; }
    }
}
