//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementosDeTipoTarifa
    {
        public int id { get; set; }
        public Nullable<int> idTipoTarifa { get; set; }
        public Nullable<int> IdTipoElemento { get; set; }
        public int valor { get; set; }
    
        public virtual TiposElemento TiposElemento { get; set; }
        public virtual TiposTarifa TiposTarifa { get; set; }
    }
}
