//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoDeCuentaOperador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoDeCuentaOperador()
        {
            this.DetallesECOperadors = new HashSet<DetallesECOperador>();
        }
    
        public int id { get; set; }
        public int idOperador { get; set; }
        public int TotalMinutosEntrantes { get; set; }
        public int TotalMinutosSalientes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesECOperador> DetallesECOperadors { get; set; }
        public virtual Operador Operador { get; set; }
    }
}
