//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionFamiliar
    {
        public int id { get; set; }
        public int ClienteDe { get; set; }
        public int ClienteA { get; set; }
        public int idTipoRelacionesFamiliar { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual TipoRelacionesFamiliar TipoRelacionesFamiliar { get; set; }
    }
}
