//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposElemento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposElemento()
        {
            this.ElementosDeTipoTarifas = new HashSet<ElementosDeTipoTarifa>();
            this.TipoElementoFijoes = new HashSet<TipoElementoFijo>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public int IdTipoUnidad { get; set; }
        public bool EsFijo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementosDeTipoTarifa> ElementosDeTipoTarifas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoElementoFijo> TipoElementoFijoes { get; set; }
        public virtual TiposUnidad TiposUnidad { get; set; }
    }
}
